server.address=127.0.0.1
server.port=8088
spring.datasource.url=jdbc:h2:mem:main;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
server.servlet.session.timeout=30m
server.error.include-message=never
spring.jackson.time-zone=America/Lima
