spring.datasource.url=${MAIN_DB_URL:jdbc:mysql://127.0.0.1:3306/main_s08_jery?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Lima}
spring.datasource.username=${MAIN_DB_USER:root}
spring.datasource.password=${MAIN_DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=never
